// TiendaAngular2/src/app/component/main/detalle-producto/detalle-producto.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { DataApiService } from 'src/app/service/data-api.service';
import { ProductoInterface } from 'src/app/model/ProductoInterface';

@Component({
  selector: 'app-detalle-producto',
  templateUrl: './detalle-producto.component.html',
  styleUrls: ['./detalle-producto.component.css']
})
export class DetalleProductoComponent implements OnInit {
  
  constructor(
    private route: ActivatedRoute,
    private dataApi: DataApiService
  ) { }
  public producto = {};

  ngOnInit() {
    let id = this.route.snapshot.params['id'];
    this.getDetalleProducto(id);
  }

  getDetalleProducto(idProducto: string){
    this.dataApi.getOneProducto(idProducto).subscribe( producto => {
      console.dir(producto);
      this.producto = producto;
    });
  }

}

<div class="container p-3">
    <div class="header">
        <h2 class="float-left text-uppercase">{{producto.nombre}}</h2>
        <div class="float-right">
            <a [routerLink]="['../../lista']" class="btn btn-light" id="button-addon1"><i class="far fa-hand-point-left"></i>&nbsp;&nbsp;Atrás</a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-6">
            <img src="{{producto.imagenUrl}}" class="w-100" alt="...">
        </div>
        <div class="col-6 detalle">
            <div>{{producto.descripcion}}</div>
            <hr>
            <div><strong>Precio:</strong> S/. {{producto.precio}}</div>
            <div><strong>Unidades disponibles:</strong> {{producto.disponible}}</div>
        </div>
    </div>
</div>

// TiendaReact/src/components/main/DetalleProducto/DetalleProducto.jsx
import React, { Component } from 'react';
import './DetalleProducto.css';
import firebase from 'firebase';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHandPointLeft } from '@fortawesome/free-solid-svg-icons';

class DetalleProducto extends Component{
    constructor(props){
        super(props);
        this.producto = {};
        this.state = {
            producto: {}
        }
    }
    getOneProducto(){
        let idProducto = this.props.id;
        firebase.firestore().doc(`productos/${idProducto}`).onSnapshot(snapshot => {
            if(snapshot.exists === false){
                this.setState({producto: null});
            }
            else{
                const data = snapshot.data();
                data.id = snapshot.id;
                this.producto = data;
                this.setState({producto: this.producto});
            }
            
        })
        if(this.state.producto == null){
            window.location.href = '/main';
        }
        else{
        return (
            <div className="container p-3">
                <div className="header">
                    <h2 className="float-left text-uppercase">{this.state.producto.nombre}</h2>
                    <div className="float-right">
                        <Link to={'/main'} className="btn btn-light" id="button-addon1"><FontAwesomeIcon icon={faHandPointLeft}></FontAwesomeIcon>&nbsp;&nbsp;Atrás</Link>
                    </div>
                </div>
                <hr />
                <div className="row">
                    <div className="col-6">
                        <img src={this.state.producto.imagenUrl} className="w-100" alt="..." />
                    </div>
                    <div className="col-6 detalle">
                        <div>{this.state.producto.descripcion}</div>
                        <hr />
                        <div><strong>Precio:</strong> S/. {this.state.producto.precio}</div>
                        <div><strong>Unidades disponibles:</strong> {this.state.producto.disponible}</div>
                    </div>
                </div>
            </div>
        )
        }
    }
    render(){
        return(
            <div component-detalleproducto="">
                {
                    this.getOneProducto()
                }
            </div>
        )
    }
}

export default DetalleProducto;
