// TiendaAngular2/src/app/component/main/carrito/carrito.component.ts
import { Component, OnInit } from '@angular/core';
import { DataApiService } from 'src/app/service/data-api.service';
import { CarritoInterface } from 'src/app/model/CarritoInterface';

@Component({
  selector: 'app-carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css']
})
export class CarritoComponent implements OnInit {

  constructor(private dataApi: DataApiService) { }

  public carrito: CarritoInterface[] = [];
  public totalPagar: number = 0;

  ngOnInit() {
    this.carrito = this.dataApi.getCarrito();
    this.carrito.map(producto => {
      this.totalPagar += producto.subtotal;
    })
  }

  pagarCarrito(){
    this.carrito.map(producto => {

      this.dataApi.updateStock(producto.id, producto.cantidad).then(value => console.log("asdsadasdasd",value));
    });
    this.dataApi.payCarrito();
  }

}

<div class="container p-3">
    <div class="header">
        <h2><i class="fas fa-shopping-cart"></i> Carrito de compras <span class="badge badge-success">{{this.dataApi.getTotalCarrito()}}</span></h2>
    </div>
    <hr>
    <div class="row">
        <div class="col-9">
            <div *ngFor="let producto of this.carrito; let i = index">
                <div class="row item-producto">
                    <div class="col-3">
                        <img src="{{producto.imagenUrl}}" class="w-100" alt="...">
                    </div>
                    <div class="col-6 detalle">
                        <h3 class="font-weight-bold text-uppercase">{{producto.nombre}}</h3>
                        <div><strong>Cantidad:</strong> {{producto.cantidad}}</div>
                        <div><strong>Precio unitario:</strong> {{producto.precio}}</div>
                        <div><strong>Subtotal:</strong> S/. {{producto.subtotal}}</div>
                    </div>
                </div>
                <hr>
            </div>
        </div>
        <div class="col-3">
            <div class="totalCarrito">
                <div>Total a pagar</div>
                <div class="totalPagar">S/. {{this.totalPagar | number}}</div>
                <button type="button" class="btn btn-success w-100" (click)="pagarCarrito()"><i class="fas fa-money-bill-wave"></i> PAGAR</button>
            </div>
        </div>
    </div>
    
</div>

// TiendaReact/src/components/main/Carrito/Carrito.jsx
import React, { Component } from 'react';
import firebase from 'firebase';
import './Carrito.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faShoppingCart } from '@fortawesome/free-solid-svg-icons';

class Carrito extends Component {

    componentWillMount(){
        this.getTotalPagarCarrito();
    }
    constructor(){
        super();
        this.state = {
            totalPagar: 0
        }
        this.producto = [];
        this.payCarrito = this.payCarrito.bind(this);
    }

    getCarrito(){
        if(sessionStorage.getItem('carrito')){
          return JSON.parse(sessionStorage.getItem('carrito'))
        }
        return [];
    }

    getTotalCarrito(){
        return this.getCarrito().length;
    }

    getTotalPagarCarrito(){
        let totalPagar = 0;
        this.getCarrito().map(producto => {
            totalPagar += producto.subtotal;
            this.setState({ totalPagar: totalPagar });
        });
    }

    getProductosCarrito(){
         return this.getCarrito().map( producto => {
            
             return (
                <div key={producto.id}>
                    <div className="row item-producto">
                        <div className="col-3">
                            <img src={process.env.PUBLIC_URL + producto.imagenUrl} className="w-100" alt="..." />
                        </div>
                        <div className="col-6 detalle">
                            <h3 className="font-weight-bold text-uppercase">{producto.nombre}</h3>
                            <div><strong>Cantidad:</strong> {producto.cantidad}</div>
                            <div><strong>Precio unitario:</strong> {producto.precio}</div>
                            <div><strong>Subtotal:</strong> S/. {producto.subtotal}</div>
                        </div>
                    </div>
                    <hr />
                </div>
            )
         });
    }

    updateStock(producto){
        producto.disponible -= producto.cantidad;
        let productoDoc = firebase.firestore().doc(`productos/${producto.id}`);
        productoDoc.update(producto);
    }

    payCarrito(event){
        this.getCarrito().map( producto => {
            let idProducto = producto.id;
            this.updateStock(producto);
            console.log(producto);
        });
        setTimeout(function(){
            sessionStorage.removeItem('carrito');
            window.location.href = '/main';
        }, 500);
    }

    render(){
        return (
            <div component-carrito="">
                <div className="container p-3">
                    <div className="header">
                        <h2><FontAwesomeIcon icon={faShoppingCart}></FontAwesomeIcon> Carrito de compras <span className="badge badge-success">{this.getTotalCarrito()}</span></h2>
                    </div>
                    <hr />
                    <div className="row">
                        <div className="col-9">
                            {
                                this.getProductosCarrito()
                            }
                        </div>
                        <div className="col-3">
                            <div className="totalCarrito">
                                <div>Total a pagar</div>
                                <div className="totalPagar">S/. {this.state.totalPagar}</div>
                                <button type="button" className="btn btn-success w-100" onClick={this.payCarrito}><i className="fas fa-money-bill-wave"></i> PAGAR</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

export default Carrito;
