// TiendaAngular2/src/app/component/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from 'src/environments/environment';
import { DataApiService } from 'src/app/service/data-api.service';
import { AuthService } from 'src/app/service/auth.service';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  constructor(private authService: AuthService, private dataApi: DataApiService, private route: Router) { }
  ngOnInit() {
    
  }

  logout(){
    this.authService.logoutUser();
  }

  carrito(){
    this.route.navigateByUrl('main(principal:carrito)')
  }

  principal(){
    this.route.navigateByUrl('main(principal:lista)')
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#"><i class="fas fa-store-alt"></i> Tienda Angular/React</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link pointer" (click)="principal()"><i class="fas fa-boxes"></i> Principal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link pointer" (click)="carrito()"><i class="fas fa-shopping-cart"></i> Carrito <span class="badge badge-success">{{this.dataApi.getTotalCarrito()}}</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link pointer" (click)="logout()"><i class="fas fa-sign-out-alt"></i> Salir</a>
            </li>
        </ul>
    </div>
</nav>

// TiendaReact/src/components/NavBar.jsx
import React, { Component } from "react";
import { Navbar, Nav, Badge, NavItem } from 'react-bootstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faStoreAlt, faBoxes, faShoppingCart, faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
import './NavBar.css';
 
class NavBar extends Component{

    constructor(props){
        super(props);
        this.logout = this.logout.bind(this);
    }
    
    logout(){
        sessionStorage.removeItem("currentuser");
        this.props.onVerifySession();
    }

    render(){
        return(
            <div component-navbar="">
                <Navbar bg="light" expand="lg" fixed="top">
                    <Navbar.Brand href="#home"><FontAwesomeIcon icon={faStoreAlt}></FontAwesomeIcon> Tienda Angular/React</Navbar.Brand>
                    <Navbar.Toggle aria-controls="basic-navbar-nav" />
                    <Navbar.Collapse id="basic-navbar-nav">
                        <Nav className="ml-auto">
                            <NavItem>
                                <Nav.Link href="/main"><FontAwesomeIcon icon={faBoxes}></FontAwesomeIcon> Principal</Nav.Link>
                            </NavItem>
                            <NavItem>
                                <Nav.Link href="/carrito"><FontAwesomeIcon icon={faShoppingCart}></FontAwesomeIcon> Carrito <Badge variant="success">{this.props.totalCarrito}</Badge></Nav.Link>
                            </NavItem>
                            <NavItem>
                                <Nav.Link onClick={this.logout}><FontAwesomeIcon icon={faSignOutAlt}></FontAwesomeIcon> Salir</Nav.Link>
                            </NavItem>
                        </Nav>
                    </Navbar.Collapse>
                </Navbar>
            </div>
        )
    }
}

export default NavBar;
